FROM eclipse-temurin:17-jdk AS builder

WORKDIR /sources
COPY ./gradle /sources/gradle
COPY ./gradlew /sources
COPY ./Havana-Server/ /sources/Havana-Server
COPY ./Havana-Web/ /sources/Havana-Web
COPY ./settings.gradle /sources

RUN ./gradlew build
RUN cd Havana-Web/build/distributions && tar xf Havana-Web.tar

FROM eclipse-temurin:17-jre

WORKDIR /havana-web/bin
COPY ./tools/docker/web-entrypoint.sh run.sh
RUN chmod +x run.sh

COPY --from=builder /sources/Havana-Web/build/distributions/Havana-Web /havana-web
RUN ./Havana-Web

ENTRYPOINT ["/havana-web/bin/run.sh"]
