FROM eclipse-temurin:17-jdk AS builder

WORKDIR /sources
COPY ./gradle /sources/gradle
COPY ./gradlew /sources
COPY ./Havana-Server/ /sources/Havana-Server
COPY ./settings.gradle /sources

RUN ./gradlew build
RUN cd Havana-Server/build/distributions && tar xf Havana-Server.tar

FROM eclipse-temurin:17-jre

WORKDIR /havana-server/bin
COPY ./figuredata.xml .
COPY ./tools/snowstorm_maps ./tools/snowstorm_maps
COPY ./tools/docker/server-entrypoint.sh run.sh
RUN chmod +x run.sh

COPY --from=builder /sources/Havana-Server/build/distributions/Havana-Server /havana-server
RUN ./Havana-Server

ENTRYPOINT ["/havana-server/bin/run.sh"]
